[versions]
spotless-gradle = "8.0.0"
blowdryer-gradle = "1.7.1"
develocity = "4.0.3"
jackson = "2.20.1"
jfrog-gradle = "6.0.2"
gradle-plugin-shadow = "9.2.2"
gradle-license-report = "3.0.1"


[libraries]
diffplug-spotless = { module = "com.diffplug.spotless:spotless-plugin-gradle", version.ref = "spotless-gradle" }
diffplug-blowdryer-setup = { module = "com.diffplug.blowdryerSetup:com.diffplug.blowdryerSetup.gradle.plugin", version.ref = "blowdryer-gradle" }
develocity = { module = "com.gradle.develocity:com.gradle.develocity.gradle.plugin", version.ref = "develocity" }
jfrog-buildinfo-gradle = { module = "org.jfrog.buildinfo:build-info-extractor-gradle", version.ref = "jfrog-gradle" }
shadow = { module = "com.gradleup.shadow:com.gradleup.shadow.gradle.plugin", version.ref = "gradle-plugin-shadow" }
jackson-bom = { module = "com.fasterxml.jackson:jackson-bom", version.ref = "jackson" }
license-report = { module = "com.github.jk1:gradle-license-report", version.ref = "gradle-license-report" }

[plugins]
spotless = { id = "com.diffplug.spotless", version.ref = "spotless-gradle" }
develocity = { id = "com.gradle.develocity", version.ref = "develocity" }
